version: 2

multi-ecosystem-groups:
  all:
    schedule:
      cronjob: 0 2 * * 1
      interval: cron

updates:
  - directory: /
    package-ecosystem: github-actions
    multi-ecosystem-group: all
    patterns: ["*"]
